server:
  port: ${PORT:8089}

spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER:http://localhost:8081/realms/maqsat}

keycloak:
  admin:
    base-url: ${KEYCLOAK_BASE_URL:http://localhost:8081}
    realm: ${KEYCLOAK_REALM:maqsat}
    client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:maqsat-admin}
    client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:maqsat-admin-secret}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      show-details: always
  otlp:
    tracing:
      endpoint: ${MANAGEMENT_OTLP_TRACING_ENDPOINT:http://localhost:4318/v1/traces}
  tracing:
    sampling:
      probability: 1.0

springdoc:
  swagger-ui:
    path: /swagger-ui.html

logging:
  structured:
    format:
      console: ecs
