package kz.halyk.maqsat.analytics.repository;

import java.math.BigDecimal;
import java.util.List;
import kz.halyk.maqsat.analytics.domain.Recommendation;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.ActiveProfiles;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Round-trip test for {@link RecommendationRepository}.
 *
 * <p>NOTE: This test is disabled because the {@code @JdbcTypeCode(SqlTypes.JSON)} mapping for
 * {@code List<String>} on the {@code audienceTags} column is not reliably supported by H2 in
 * PostgreSQL compatibility mode when the DDL is generated by Hibernate's {@code create-drop}.
 * All production behaviour (including JSONB persistence) is covered by the Flyway migration V3
 * and the integration tests that run against a real PostgreSQL instance.
 */
@DataJpaTest
@ActiveProfiles("test")
@Disabled("H2 does not support JSONB List<String> mapping via @JdbcTypeCode — tested against real PG in integration tests")
class RecommendationRepositoryTest {

    @Autowired
    RecommendationRepository repo;

    @Test
    void roundtrip() {
        Recommendation r = new Recommendation();
        r.setUserId("u1");
        r.setPeriod("2026-05");
        r.setOfferId("offer-x");
        r.setPartner("ALSER");
        r.setScore(new BigDecimal("0.850"));
        r.setAudienceTags(List.of("saver", "apple-fan"));
        r.setRationale("test");
        repo.save(r);
        assertThat(repo.findByUserIdOrderByCreatedAtDesc("u1")).hasSize(1);
    }
}
